tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/fuse'
tap 'homebrew/services'
tap 'rcmdnk/file'
cask 'java'
cask 'osxfuse'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash-completion'
brew 'bash-git-prompt'
brew 'boost'
brew 'go'
brew 'docker'
brew 'docker-machine', restart_service: true
brew 'libyaml'
brew 'docker-compose'
brew 'gdbm'
brew 'gettext'
brew 'git-flow'
brew 'libffi'
brew 'pcre'
brew 'pkg-config'
brew 'glib'
brew 'htop'
brew 'openssl'
brew 'httping'
brew 'hub'
brew 'jetty'
brew 'libtool'
brew 'mas'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'mercurial'
brew 'mycli'
brew 'mysql', restart_service: true
brew 'nginx'
brew 'nmap'
brew 'node'
brew 'nodebrew'
brew 'postgresql'
brew 'pyenv'
brew 'qt'
brew 'ruby-build'
brew 'rbenv'
brew 'source-highlight'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'homebrew/fuse/sshfs'
cask 'clipy'
cask 'cyberduck'
cask 'firefoxdeveloperedition'
cask 'google-play-music-desktop-player'
cask 'java7'
cask 'mysqlworkbench'
cask 'rubymine'
cask 'slack'
cask 'sshfs'
cask 'virtualbox'
mas 'PhotoScapeX', id: 929507092
mas 'Kobito', id: 896624060
mas 'iMovie', id: 408981434
mas 'Pages', id: 409201541
mas 'GarageBand', id: 682658836
mas 'Keynote', id: 409183694
mas 'Bear', id: 1091189122
mas 'Numbers', id: 409203825
