
# tap repositories and their packages

tap 'homebrew/core'
brew 'adwaita-icon-theme'
brew 'amazon-ecs-cli'
brew 'atk'
brew 'aws-shell'
brew 'awscli'
brew 'bash'
brew 'bash-completion@2'
brew 'bash-git-prompt'
brew 'bitwarden-cli'
brew 'boost'
brew 'circleci'
brew 'cmake'
brew 'coreutils'
brew 'direnv'
brew 'envchain'
brew 'fish'
brew 'fontconfig'
brew 'fzf'
brew 'gcc'
brew 'gd'
brew 'gdbm'
brew 'gdk-pixbuf'
brew 'geckodriver'
brew 'gettext'
brew 'ghq'
brew 'git'
brew 'git-flow'
brew 'glib'
brew 'glide'
brew 'gmp'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-units', args: ['with-default-names']
brew 'go'
brew 'gobject-introspection'
brew 'graphite2'
brew 'gtk+'
brew 'gtk+3'
brew 'gtksourceview3'
brew 'htop'
brew 'httping'
brew 'httpstat'
brew 'hub'
brew 'ideviceinstaller'
brew 'imagemagick@6'
brew 'iperf'
brew 'isl'
brew 'jpeg'
brew 'jpegoptim'
brew 'jq'
brew 'json-c'
brew 'lame'
brew 'libcroco'
brew 'libepoxy'
brew 'libevent'
brew 'libffi'
brew 'libidn2'
brew 'libimobiledevice'
brew 'libmpc'
brew 'libnet'
brew 'libpcap'
brew 'libplist'
brew 'libpng'
brew 'libpq'
brew 'librsvg'
brew 'libsass'
brew 'libtasn1'
brew 'libtiff'
brew 'libtool'
brew 'libunistring'
brew 'libusb'
brew 'libyaml'
brew 'libyubikey'
brew 'libzip'
brew 'little-cms2'
brew 'lv'
brew 'makedepend'
brew 'mas'
brew 'meson-internal'
brew 'mitmproxy'
brew 'mpfr'
brew 'mscgen'
brew 'mycli'
brew 'mysql@5.7'
brew 'net-snmp'
brew 'nginx'
brew 'ninja'
brew 'nkf'
brew 'nmap'
brew 'node'
brew 'node-build'
brew 'nodenv'
brew 'nspr'
brew 'nss'
brew 'oniguruma'
brew 'openjpeg'
brew 'openssl@1.1'
brew 'optipng'
brew 'packer'
brew 'pango'
brew 'pcre'
brew 'pcre2'
brew 'peco'
brew 'pgcli'
brew 'pixman'
brew 'pkg-config'
brew 'poppler'
brew 'postgresql'
brew 'protobuf'
brew 'pv'
brew 'py2cairo'
brew 'py3cairo'
brew 'pyenv'
brew 'pygobject3'
brew 'python'
brew 'python@2'
brew 'rails-completion'
brew 'rancher-compose'
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'ruby-build'
brew 'shared-mime-info'
brew 'source-highlight'
brew 'speedtest-cli'
brew 'sphinx-doc'
brew 'sqlite'
brew 'stern'
brew 'swagger-codegen'
brew 'teensy_loader_cli'
brew 'terminal-notifier'
brew 'terraformer'
brew 'tfenv'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'unzip'
brew 'watch'
brew 'watchman'
brew 'webp'
brew 'wget'
brew 'x264'
brew 'xonsh'
brew 'xvid'
brew 'xz'
brew 'yarn'
brew 'ykpers'

tap 'homebrew/bundle'

tap 'homebrew/cask-versions'
cask 'docker-edge'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'alfred'
cask 'bitwarden'
cask 'clipy'
cask 'cyberduck'
cask 'geektool'
cask 'hammerspoon'
cask 'hyperswitch'
cask 'iterm2'
cask 'java'
cask 'meld'
cask 'pocket-casts'
cask 'segger-embedded-studio-for-arm'
cask 'skitch'
cask 'slack'
cask 'station'
cask 'visual-studio-code'
cask 'zeplin'

tap 'argon/mas'

tap 'buo/cask-upgrade'

tap 'delphinus/sfmono-square'
brew 'sfmono-square'

tap 'derailed/k9s'
brew 'k9s'

tap 'knqyf263/pet'
brew 'pet'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'remind101/formulae'
brew 'assume-role'

tap 'thoughtbot/formulae'
brew 'rcm'

# Other Homebrew packages
brew 'kubernetes-helm'
brew 'mongodb'
brew 'openssl'
brew 'qt@5.5'
brew 'usbmuxd'

# Other Cask applications
cask 'arduino'
cask 'boostnote'
cask 'chromedriver'
cask 'coteditor'
cask 'gimp'
cask 'google-japanese-ime'
cask 'https://raw.githubusercontent.com/Homebrew/homebrew-cask/b88346667547cc85f8f2cacb3dfe7b754c8afc8a/Casks/gcc-arm-embedded.rb'
cask 'java8'
cask 'marshallofsound-google-play-music-player'
cask 'mysqlworkbench'
cask 'sketch'
cask 'teensy'
cask 'vlc'

# App Store applications
mas 'GarageBand', id: id:
mas 'iMovie', id: id:
mas 'Magnet', id: id:
mas 'Pages', id: id:
mas 'Xcode', id: id:
